### ISSUE TITLE
Add single-amino-acid basis functions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/variational#1]
- add a folder (not a package) under variational/basissets
- add each single-amino-acid basis set (right eigenvectors) as a binary file. Please use compressed npz, this is created by np.savez(X, compressed=True), and can be loaded as usual by np.load(filename). It is very important to use compressed files (otherwise we blow up the history of the git repository, and the repository becomes useless), and also to use binary instead of text files (text files will count as code and ruin the language statistics)
- these files are opened in the **init** functions of the Single-Amino-Acid Basis set object.
- Please, do that in a separate branch (e.g. git checkout -b devel). Once this is clean we can do a pull request and merge that branch to master. This is the minimal policy for avoiding to create a chaos. In pyEMMA we use a somewhat more advanced policy, but for the variational package that's fine for now.

**Comment by fnueske** [comment]
As we were talking about basis sets in the other thread: This issue has been completed long ago, hasn't it?

**Comment by franknoe** [comment]
yes, thanks.
