### ISSUE TITLE
Installation fails: No module named versioneer.

### ISSUE THREAD

**Issue by fnueske** [markovmodel/variational#15]
Cannot install the package using python setup.py install because of this error message.

**Comment by cwehmeyer** [comment]
added versioneer installation to the repository

**Comment by fnueske** [comment]
The installation works now. However, whenever I try to import the module, I get this error message:

## import variational

ImportError                               Traceback (most recent call last)
<ipython-input-3-45ebeb1d5775> in <module>()
----> 1 import variational

/Users/fnueske/Documents/Uni/variational/variational/**init**.py in <module>()
      3 # import subpackages such that they are available after the main package import
      4 import basissets
----> 5 import estimators
      6 import solvers
      7 

/Users/fnueske/Documents/Uni/variational/variational/estimators/**init**.py in <module>()
      1 **author** = 'noe'
      2 
----> 3 from moments import RunningCovar

/Users/fnueske/Documents/Uni/variational/variational/estimators/moments.py in <module>()
     73 import math, sys, numbers
     74 import numpy as np
---> 75 from variational.estimators.covar_c import covartools
     76 import warnings
     77 

ImportError: cannot import name covartools

Frank, can you have a look at it?

**Comment by marscher** [comment]
invoke
`python setup.py develop`
to compile the binary extensions.

**Comment by fnueske** [comment]
Thanks, that works.
