### ISSUE TITLE
symmetrized running_covar gives unexpected results

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/variational#28]
The following test shows a difference of \approx 1 between the implementation result and the reference.
Am I using running_covar the correct way?

``` Python
import numpy as np
import variational

def mymean(X,Y):
    return 0.5*(np.mean(X, axis=0)+np.mean(Y, axis=0))

def mycov(data, mean):
    return (data-mean).T.dot(data-mean) / (data.shape[0]-1)

n_frames = 50
dim = 10
white = np.random.randn(n_frames, dim)
data = np.dot(white, np.random.randn(dim,dim))

X=data[1:,:]
Y=data[0:-1,:]

mean = mymean(Y,X)
cov_ref = 0.5*(mycov(X,mean) + mycov(Y,mean))

covar = variational.estimators.running_covar(xx=True, xy=True, yy=False,
                              remove_mean=True, symmetrize=True)
covar.add(X=X, Y=Y)
cov_test = covar.cov_XX()

print np.max(np.abs(cov_ref-cov_test))
```

Edit: calculation of reference result was incorrect in the original post.

**Comment by franknoe** [comment]
This looks correct. Can we narrow it down? Does the problem occur with symmetrization?

**Comment by fabian-paul** [comment]
Correlation in my example was computed the wrong way. This test succeeds:

``` Python
import numpy as np
import variational

def mymean(X,Y):
    return 0.5*(np.mean(X, axis=0)+np.mean(Y, axis=0))

n_frames = 50
dim = 10
white = np.random.randn(n_frames, dim)
data = np.dot(white, np.random.randn(dim,dim))

X=data[1:,:]
Y=data[0:-1,:]

mean = mymean(Y,X)

cov_ref = ((X-mean).T.dot(X-mean) + (Y-mean).T.dot(Y-mean)) / ((2*X.shape[0])-1)

covar = variational.estimators.running_covar(xx=True, xy=True, yy=False,
                              remove_mean=True, symmetrize=True)
covar.add(X=X, Y=Y)
cov_test = covar.cov_XX()

print np.max(np.abs(cov_ref-cov_test))
```

**Comment by franknoe** [comment]
Ah - was the factor 2 missing?

Am 07/01/16 um 18:51 schrieb fabian-paul:

> Correlation in my example was computed the wrong way. This test succeeds:
> 
> import  numpyas  np
> import  variational
> 
> def  mymean(X,Y):
>      return  0.5*(np.mean(X,axis=0)+np.mean(Y,axis=0))
> 
> n_frames=  50
> dim=  10
> white=  np.random.randn(n_frames, dim)
> data=  np.dot(white, np.random.randn(dim,dim))
> 
> X=data[1:,:]
> Y=data[0:-1,:]
> 
> mean=  mymean(Y,X)
> 
> cov_ref=  ((X-mean).T.dot(X-mean)+  (Y-mean).T.dot(Y-mean))/  ((2*X.shape[0])-1)
> 
> covar=  variational.estimators.running_covar(xx=True,xy=True,yy=False,
>                                remove_mean=True,symmetrize=True)
> covar.add(X=X,Y=Y)
> cov_test=  covar.cov_XX()
> 
> print  np.max(np.abs(cov_ref-cov_test))
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/issues/28#issuecomment-169755051.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
I first computed the normalizing factor as 2_(len(X)-1) while it should be 2_len(X)-1.

**Comment by franknoe** [comment]
hmm ... is it? Or is my version wrong?

Am 07/01/16 um 19:32 schrieb fabian-paul:

> I first computed the normalizing factor as 2/(len(X)-1) while it 
> should be 2/len(X)-1.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/issues/28#issuecomment-169764950.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
Honestly I think both are wrong because we use correlated data. (Subtracting one doesn't make the estimate unbiased in our case). I'm fine with sticking with 2len(X)-1 (your version).

**Comment by franknoe** [comment]
I'm not sure if we need uncorrelated data for the -1 argument. It's 
about degree of freedoms. But thinking about it I think it should be

M_sym = 0.5 \* (X^T X + Y^T Y)
C_sym = M_sym / (len(X) - 1)

which would mean we have to do 2len(X) - 2, or I should rather do the 
0.5 operation which is currently avoided.

I think for TICA it's irrelevant because the covariance matrices on both 
sides are divided by the same factor. Ah, and I think for TICA we also 
don't need to use the covariance matrices but can use the moment 
matrices directly (saves the normalization step).

Am 07/01/16 um 19:37 schrieb fabian-paul:

> Honestly I think both are wrong because we use correlated data. 
> (Subtracting one doesn't make the estimate unbiased in our case). I'm 
> fine with sticking with 2len(X)-1 (your version).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/variational/issues/28#issuecomment-169766797.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
