### ISSUE TITLE
remove subdir basissets

### ISSUE THREAD

**Issue by franknoe** [markovmodel/variational#37]
Since the basis sets are in a separate repository now, we should remove all basissets stuff from this repo. There's still:

https://github.com/markovmodel/variational/tree/master/variational/basissets

**Comment by marscher** [comment]
@fnueske After your latest PR is merged, can you please ensure that you push your local branches to remote, so I can safely rewrite the history?

**Comment by fnueske** [comment]
@marscher , as soon as the latest PR is merged, you can go ahead.
